config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  #match routes
  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  # "to" is to what controller and what action, "as" is the prefix in rails routes
  get 'show/:permalink', to: 'public#show', as: "public_show"
  
  resources :admin_users, except: [:show] do
    member do
      get :delete
    end
  end
  resources :pages do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
 	get 'demo/escape_output'
 	#default route, may become depracated
 	#get ":controller(/:action(/:id))"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  
  layout "admin"
  before_action :confirm_logged_in, except: [:login, :attempt_login, :logout]

  def menu
    @username = session[:username]
  end

  def login
  	#login form
  end

  def attempt_login
  	if params[:username].present? && params[:password].present?
  		found_user = AdminUser.where(username: params[:username]).first
  		if found_user
  			authorized_user = found_user.authenticate(params[:password])
  		end
  	end

  	if authorized_user
  		session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
  		flash[:notice] = "You are now logged in"
  		redirect_to admin_path
  	else
  		flash.now[:notice] = "Invalid username/password combination"
  		render "login"
  	end
   end

  def logout
  	session[:user_id] = nil
    session[:username] = nil
  	flash[:notice] = "You have been successfully logged out"
  	redirect_to access_login_path
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<% @page_title = "Admin Login" %>

<div class="login">
	<%= form_tag(access_attempt_login_path, method: :post) do %>

	<table>
		<tr>
			<td><%= label_tag(:username) %></td>
			<td><%= text_field_tag(:username, params[:username]) %></td>
		</tr>
		<tr>
			<td><%= label_tag(:password) %></td>
			<td><%= password_field_tag(:password) %></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><%= submit_tag("Log In") %></td>
		</tr>
	</table>
	<% end %>
</div>

app/views/access/menu.html.erb
<% @page_title = "Admin Menu" %>

<div class="menu">
	<h2>Admin Menu</h2>
	<div class="identity">Logged In As: <%= @username %></div>
	<ul>
		<li><%= link_to("Manage content", subjects_path) %></li>
		<li><%= link_to("Manage Admin Users", admin_users_path) %></li>
		<li><%= link_to("Logout", access_logout_path) %></li>
	</ul>
</div>