config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  #match routes
  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  # "to" is to what controller and what action, "as" is the prefix in rails routes
  get 'show/:permalink', to: 'public#show', as: "public_show"
  
  resources :admin_users, except: [:show] do
    member do
      get :delete
    end
  end
  resources :pages do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
 	get 'demo/escape_output'
 	#default route, may become depracated
 	#get ":controller(/:action(/:id))"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :pages

	acts_as_list

	scope :visible, lambda {where(visible: true)}
	scope :invisible, lambda {where(visible: false)}
	scope :sorted, lambda {order("position ASC")}
	scope :newest_first, lambda {order("created_at DESC")}
	scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}

	validates_presence_of :name
	validates_length_of :name, maximum: 255


end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'admin'
  
  before_action :confirm_logged_in
  before_action :set_subject_count, only: [:new, :create, :edit, :update]

  def index
    logger.debug("*******testing debug *******")
    @subjects = Subject.all.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] = "Subject created successfully"
      redirect_to subjects_path
    else
      render("new")
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      flash[:notice] = "Subject updated successfully"
      redirect_to subject_path(@subject)
    else
      render("edit")
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' deleted successfully"
    redirect_to subjects_path
  end

  private

  def set_subject_count
    @subject_count = Subject.count
    if params[:action] == 'new' || params[:action] == 'create'
      @subject_count += 1
    end
  end

  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_subject_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@subject_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Created</th>
    <td><%= f.datetime_select(:created_at, order: [:month, :day, :year]) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<h1>Subjects#delete</h1>
<p>Find me in app/views/subjects/delete.html.erb</p>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render partial: "subject_form", locals: {f: f} %>
    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<% @page_title = "All Subjects" %>

<%= link_to("<< Back to Menu", admin_path, class: 'back-link') %>

<div class="subjects index">
	<h2>Subjects</h2>

	<%= image_tag "plus_sign.png", size: '11x11', alt: '+' %>
	<%= link_to("Add New Subjects", new_subject_path, class: 'action new') %>

	<table class="listing" summary="Subject list">
		<tr class="header">
			<th>#</th>
			<th>Subject</th>
			<th>Visible</th>
			<th>Pages</th>
			<th>Actions</th>
		</tr>
		<% @subjects.each do |subject| %>
		<tr>
			<td><%= subject.position %></td>
			<td><%= subject.name %></td>
			<td class="center"><%= status_tag(subject.visible)%></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
      	<%= link_to("View Pages", pages_path(subject_id: subject.id), :class => 'action show') %>
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>

	</table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render partial: 'subject_form', locals: {f: f} %>
    
    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>