config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  #match routes
  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  # "to" is to what controller and what action, "as" is the prefix in rails routes
  get 'show/:permalink', to: 'public#show', as: "public_show"
  
  resources :admin_users, except: [:show] do
    member do
      get :delete
    end
  end
  resources :pages do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
 	get 'demo/escape_output'
 	#default route, may become depracated
 	#get ":controller(/:action(/:id))"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
	has_and_belongs_to_many :pages
	has_many :section_edits
	has_many :sections, :through => :section_edits
	scope :sorted, lambda{order("last_name ASC, first_name ASC")}
	#this is users if the class name was still users and we wanted to use another table
	#self.table_name  = "admin_users"

	has_secure_password

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
	FORBIDDEN_USERNAMES = ['littlebobebop', 'humptydumpty', 'marymary']
	#sexy validations
	validates :first_name, presence: true, length: {maximum: 25}
	validates :last_name, presence: true, length: {maximum: 50}
	validates :username, length: {within: 8..25}, uniqueness: true
	validates :email, presence: true, length: {maximum: 100}, format: EMAIL_REGEX, confirmation: true


	# sexy validations
	
	validate :username_is_allowed
	validate :no_new_users_on_wednesday, on: :create

	#long form validations

=begin
  validates_presence_of :first_name
  validates_length_of :first_name, :maximum => 25
  validates_presence_of :last_name
  validates_length_of :last_name, :maximum => 50
  validates_presence_of :username
  validates_length_of :username, :within => 8..25
  validates_uniqueness_of :username
  validates_presence_of :email
  validates_length_of :email, :maximum => 100
  validates_format_of :email, :with => EMAIL_REGEX
  validates_confirmation_of :email
=end

def full_name
	"#{first_name} #{last_name}"
end

private

	def no_new_users_on_wednesday
		if Time.now.wday == 3
			errors.add(:base, 'no new users on Wednesday')
		end
	end

	def username_is_allowed
		if FORBIDDEN_USERNAMES.include?(username)
			errors.add(:username, "has been restricted from use.")
		end
	end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :confirm_logged_in

  layout "admin"

  def index
    @admin_users = AdminUser.sorted
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(admin_params)
    if @admin_user.save
      flash[:notice] = "You have created a new Admin User"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.update_attributes(admin_params)
      flash[:notice] = "User has been successfully updated"
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  def delete
    @admin_user = AdminUser.find(params[:id])
  end

  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy
    flash[:notice] = "Admin User, #{@admin_user.full_name}, has been deleted"
    redirect_to admin_users_path
  end

private

  def admin_params
    params.require(:admin_user).permit(:first_name, :last_name, :email, :username, :password)
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Admin user form fields">
	<tr>
		<th><%= f.label(:first_name) %></th>
		<td><%= f.text_field(:first_name) %></td>
	</tr>
	<tr>
		<th><%= f.label(:last_name) %></th>
		<td><%= f.text_field(:last_name) %></td>
	</tr>
	<tr>
		<th><%= f.label(:email) %></th>
		<td><%= f.text_field(:email) %></td>
	</tr>
	<tr>
		<th><%= f.label(:username) %></th>
		<td><%= f.text_field(:username) %></td>
	</tr>
	<tr>
		<th><%= f.label(:password) %></th>
		<td><%= f.password_field(:password) %></td>
	</tr>
</table>

app/views/admin_users/create.html.erb
<h1>AdminUsers#create</h1>
<p>Find me in app/views/admin_users/create.html.erb</p>

app/views/admin_users/delete.html.erb
<%= @page_title = "Delete Admin User" %>

<%= link_to("<< Back to list", admin_users_path, class: 'back-link') %>

<div class="admin-users delete">
	<h2>Delete Admin User</h2>

	<%= form_for(@admin_user, method: 'delete') do |f| %>

		<p>Are you sure you want to permanently delete this admin user?</p>

		<p class="reference-name"><%= f.object.full_name %></p>

		<div class="form-buttons">
			<%= f.submit("Delete Admin User") %>
		</div>

	<% end %>
</div>

app/views/admin_users/destroy.html.erb
<h1>AdminUsers#destroy</h1>
<p>Find me in app/views/admin_users/destroy.html.erb</p>

app/views/admin_users/edit.html.erb
<%= @page_title = "Update Admin User" %>

<%= link_to("<< Back to list", admin_users_path, class: "back-link") %>

<div class="admin-users new">
	<h2>Update Admin User</h2>

	<%= form_for(@admin_user) do |f| %>

		<%= render partial: 'form', locals: {f: f} %>

		<div class="form-buttons">
			<%= f.submit("Update Admin User") %>
		</div>
		
	<% end %>
</div>

app/views/admin_users/index.html.erb
<% @page_title = "All Admin Users" %>

<%= link_to("<< Back to Menu", admin_path, class: 'back-link') %>

<div class="admin-users index">
	<h2>Admin Users</h2>

	<%= image_tag "plus_sign.png", size: '11x11', alt: '+' %>
	<%= link_to("Add New Admin User", new_admin_user_path, class: 'action new') %>

	<div><%= pluralize(@admin_users.size, "admin user") %> found</div>

	<table class="listing" summary="Subject list">
		<tr class="header">
			<th>Username</th>
			<th>Name</th>
			<th>Email</th>
			<th>Actions</th>
		</tr>
		<% @admin_users.each do |admin_user| %>
		<tr>
			<td><%= admin_user.username %></td>
			<td><%= admin_user.full_name %></td>
			<td><%= mail_to(admin_user.email) %></td>
      <td class="actions">
        <%= link_to("Edit", edit_admin_user_path(admin_user), :class => 'action edit') %>
        <%= link_to("Delete", delete_admin_user_path(admin_user), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>

	</table>
</div>

app/views/admin_users/new.html.erb
<%= @page_title = "New Admin User" %>

<%= link_to("<< Back to list", admin_users_path, class: "back-link") %>

<div class="admin-users new">
	<h2>Create Admin Users</h2>

	<%= form_for(@admin_user) do |f| %>

		<%= render partial: 'form', locals: {f: f} %>

		<div class="form-buttons">
			<%= f.submit("Create Admin User") %>
		</div>
		
	<% end %>
</div>

app/views/admin_users/update.html.erb
<h1>AdminUsers#update</h1>
<p>Find me in app/views/admin_users/update.html.erb</p>